### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'right')

### ISSUE THREAD

**Issue by riccardolinares** [davidjerleke/embla-carousel#655]
### Bug is related to

- [ ] embla-carousel (core package)
- [ X ] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs (documentation)
- [ ] embla-carousel-docs (generator)

### Embla Carousel version

- v8.0.0-rc15

### Describe the bug

When using the browser back button to go back to a page with a slider, I am getting this error:

``` 
Uncaught TypeError: Cannot read properties of undefined (reading 'right')
    at eval (embla-carousel.esm.js:668:65)
    at Array.map (<anonymous>)
    at measureSizes (embla-carousel.esm.js:668:36)
    at ScrollSnaps (embla-carousel.esm.js:664:22)
    at Engine (embla-carousel.esm.js:1183:7)
    at createEngine (embla-carousel.esm.js:1483:20)
    at activate (embla-carousel.esm.js:1501:14)
    at EmblaCarousel (embla-carousel.esm.js:1624:3)
    at eval (embla-carousel-react.esm.js:23:85)
    at commitHookEffectListMount (react-dom.development.js:20904:23)
    at commitHookPassiveMountEffects (react-dom.development.js:22957:7)
    at commitPassiveMountOnFiber (react-dom.development.js:23062:11)
    at recursivelyTraversePassiveMountEffects (react-dom.development.js:23040:7)
    at commitPassiveMountOnFiber (react-dom.development.js:23173:9)
    at recursivelyTraversePassiveMountEffects (react-dom.development.js:23040:7)
    at commitPassiveMountOnFiber (react-dom.development.js:23173:9)
    at recursivelyTraversePassiveMountEffects (react-dom.development.js:23040:7)
    at commitPassiveMountOnFiber (react-dom.development.js:23173:9)
    at recursivelyTraversePassiveMountEffects (react-dom.development.js:23040:7)
    at commitPassiveMountOnFiber (react-dom.development.js:23173:9)
    at recursivelyTraversePassiveMountEffects (react-dom.development.js:23040:7)
    at commitPassiveMountOnFiber (react-dom.development.js:23173:9)
    at recursivelyTraversePassiveMountEffects (react-dom.development.js:23040:7)
    at commitPassiveMountOnFiber (react-dom.development.js:23059:9)
    at recursivelyTraversePassiveMountEffects (react-dom.development.js:23040:7)
    at commitPassiveMountOnFiber (react-dom.development.js:23173:9)
    at recursivelyTraversePassiveMountEffects (react-dom.development.js:23040:7)
    at commitPassiveMountOnFiber (react-dom.development.js:23059:9)
    at recursivelyTraversePassiveMountEffects (react-dom.development.js:23040:7)
    at commitPassiveMountOnFiber (react-dom.development.js:23059:9)
    at recursivelyTraversePassiveMountEffects (react-dom.development.js:23040:7)
    at commitPassiveMountOnFiber (react-dom.development.js:23059:9)
    at recursivelyTraversePassiveMountEffects (react-dom.development.js:23040:7)
    at commitPassiveMountOnFiber (react-dom.development.js:23059:9)
    at recursivelyTraversePassiveMountEffects (react-dom.development.js:23040:7)
    at commitPassiveMountOnFiber (react-dom.development.js:23173:9)
    at recursivelyTraversePassiveMountEffects (react-dom.development.js:23040:7)
    at commitPassiveMountOnFiber (react-dom.development.js:23059:9)
    at recursivelyTraversePassiveMountEffects (react-dom.development.js:23040:7)
    at commitPassiveMountOnFiber (react-dom.development.js:23059:9)
    at recursivelyTraversePassiveMountEffects (react-dom.development.js:23040:7)
    at commitPassiveMountOnFiber (react-dom.development.js:23173:9)
    at recursivelyTraversePassiveMountEffects (react-dom.development.js:23040:7)
    at commitPassiveMountOnFiber (react-dom.development.js:23173:9)
    at recursivelyTraversePassiveMountEffects (react-dom.development.js:23040:7)
    at commitPassiveMountOnFiber (react-dom.development.js:23059:9)
    at recursivelyTraversePassiveMountEffects (react-dom.development.js:23040:7)
    at commitPassiveMountOnFiber (react-dom.development.js:23173:9)
    at recursivelyTraversePassiveMountEffects (react-dom.development.js:23040:7)
    at commitPassiveMountOnFiber (react-dom.development.js:23059:9)
2redirect-boundary.js:56 
```

### CodeSandbox

https://github.com/riccardolinares/jobflix

### Steps to reproduce

1. Go to https://github.com/riccardolinares/jobflix
2. Clone the repo and install dependencies with `npm i`
3. Go to /landing , then change page and go back using the browser back button

### Expected behavior

Go back to the page without problems.

### Screenshot

Uploading embla-bug.mov…

**Comment by davidjerleke** [comment]
Hi @riccardolinares,

Can you reduce the test case in your CodeSandbox? This is mentioned as a requirement in the [contribution guidelines](https://github.com/davidjerleke/embla-carousel/blob/master/.github/CONTRIBUTING.md#bug-reports). There's too much code/stuff going on for me to effectively debug this. Thanks!

Best,
David

**Comment by zaaakher** [comment]
@riccardolinares @davidjerleke It seems the error disappears when you comment out the `img` element inside `src/components/ui/carousel/CarouselAutoplay.tsx`

![image](https://github.com/davidjerleke/embla-carousel/assets/46135573/3c332a04-9acc-493b-9751-16827fc0d944)

**Comment by zaaakher** [comment]
Just to test things out, I removed the next.js `Link` component wrapping the `img` and the error disappeared.

**Comment by davidjerleke** [comment]
@zaaakher thanksyou for the additional details and helping out. I created a new `nextjs` project locally, created a carousel and wrapped all slides with the `nextjs Link component` and still can't reproduce the error.

Can you **reduce the test case** in your CodeSandbox? This means that you should **strip unnecessary details** and create a **minimal reproduction** of the **problem**. This is mentioned as a requirement in the [contribution guidelines](https://github.com/davidjerleke/embla-carousel/blob/master/.github/CONTRIBUTING.md#bug-reports). There's too much code/stuff going on for me to effectively debug it.

> [!IMPORTANT]  
> This issue **will be deleted** if you don't answer soon.

Best,
David

**Comment by davidjerleke** [comment]
@riccardolinares last call
